### ISSUE TITLE
CI: Not testing based on target

### ISSUE THREAD

**Issue by wiktor-k** [rustyhorde/sss#7]
Hi,

I've got a question/bug report. I've noticed that the CI setup [uses `${{ matrix.target }}` meta-variable](https://github.com/rustyhorde/sss/blob/master/.github/workflows/main.yml#L135) but the `matrix` section [uses `other` key](https://github.com/rustyhorde/sss/blob/master/.github/workflows/main.yml#L48) (not `target`).

I think they should match so either use `${{ matrix.other }}` or rename or `other` keys to `target` but since I'm not a GitHub actions expert I'll leave a bug-report instead of PR :)

**Comment by CraZySacX** [comment]
Fixed with latest updates.
